# Generated by Django 4.0 on 2021-12-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toplanti_Konusu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_konu', models.CharField(max_length=50)),
                ('t_tarih', models.DateField()),
                ('t_bassaat', models.TimeField()),
                ('t_bitsaat', models.TimeField()),
                ('t_katilimcilar', models.CharField(max_length=300)),
            ],
        ),
    ]
